# Generated by Django 5.1.5 on 2026-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='About Mukto Soft', max_length=200)),
                ('title', models.CharField(default='We Are Trusted IT Solutions Provider', max_length=300)),
                ('description', models.TextField(default='With over a decade of experience, Mukto Soft has been at the forefront of technology innovation.')),
                ('description2', models.TextField(blank=True, default='Our team of seasoned professionals brings expertise across diverse technology domains.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('experience_years', models.CharField(default='10+', max_length=10)),
                ('experience_label', models.CharField(default='Years Experience', max_length=100)),
                ('feature1', models.CharField(default='Expert Development Team', max_length=200)),
                ('feature2', models.CharField(default='24/7 Technical Support', max_length=200)),
                ('feature3', models.CharField(default='Agile Methodology', max_length=200)),
                ('feature4', models.CharField(default='Quality Assurance', max_length=200)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Transform Your Business?', max_length=300)),
                ('description', models.TextField(default="Let's discuss how our technology solutions can help your business grow.")),
                ('button_text', models.CharField(default='Start a Project', max_length=100)),
                ('button_link', models.CharField(default='/contact', max_length=300)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Welcome to Mukto Soft', max_length=200)),
                ('title_line1', models.CharField(default='Innovative', max_length=300)),
                ('title_highlight', models.CharField(default='IT Solutions', max_length=200)),
                ('title_line2', models.CharField(default='for Your Business Growth', max_length=300)),
                ('description', models.TextField(default='We deliver cutting-edge technology solutions that transform businesses, boost efficiency, and drive digital innovation.')),
                ('button_primary_text', models.CharField(default='Get Started', max_length=100)),
                ('button_primary_link', models.CharField(blank=True, default='/contact', max_length=300)),
                ('button_secondary_text', models.CharField(default='Our Services', max_length=100)),
                ('button_secondary_link', models.CharField(blank=True, default='/services', max_length=300)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(help_text='e.g. Web App, Mobile, Cloud', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MuktoSoft', max_length=200)),
                ('site_name_highlight', models.CharField(default='Soft', help_text='Part of site name shown in accent color', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_description', models.TextField(blank=True, default='We help businesses transform their digital presence with custom software solutions.')),
                ('phone', models.CharField(blank=True, default='+880 1234-567890', max_length=30)),
                ('email', models.EmailField(blank=True, default='info@muktosoft.com', max_length=254)),
                ('address', models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=300)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, default='© 2026 MuktoSoft. All rights reserved.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('avatar_letter', models.CharField(blank=True, help_text='Initial letter for avatar', max_length=2)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='web', help_text='Icon key: web, mobile, cloud, security, consulting, marketing', max_length=50),
        ),
    ]
