# Generated by Django 5.1.5 on 2026-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutsection_ctasection_herosection_portfolioitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroFloatingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Fast Delivery', max_length=100)),
                ('subtitle', models.CharField(help_text='e.g. On-time deployment', max_length=200)),
                ('icon', models.CharField(choices=[('bolt', '⚡ Fast / Bolt'), ('check', '✅ Checkmark / Uptime'), ('users', '👥 Users / Support'), ('shield', '🛡️ Shield / Security'), ('cloud', '☁️ Cloud'), ('code', '💻 Code'), ('star', '⭐ Star / Quality'), ('rocket', '🚀 Rocket / Launch')], default='bolt', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Floating Card',
                'verbose_name_plural': 'Hero Floating Cards',
                'ordering': ['order'],
            },
        ),
    ]
