# Generated by Django 5.1.5 on 2026-02-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_herofloatingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_description',
            field=models.TextField(blank=True, help_text='Full detailed description shown on the service detail page'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service detail page banner image', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Auto-generated from title if left blank', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Short description shown on cards'),
        ),
    ]
