# Generated by Django 5.1.5 on 2026-02-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_detail_description_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title if left blank', max_length=200, unique=True),
        ),
    ]
