# Generated by Django 5.1.5 on 2026-02-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='mission_description',
            field=models.TextField(blank=True, default='To empower businesses with innovative software solutions that drive growth, efficiency, and digital transformation.'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_description',
            field=models.TextField(blank=True, default='To be the leading technology partner for businesses worldwide, creating impactful digital experiences that shape the future.'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_title',
            field=models.CharField(blank=True, default='Our Vision', max_length=200),
        ),
    ]
