# Generated by Django 5.1.5 on 2026-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_clientlogo_companytimeline_corevalue_faq_workprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Client photo', null=True, upload_to='testimonials/'),
        ),
    ]
