# Generated by Django 5.1.5 on 2026-02-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_productfaq_productfeature_productscreenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('period', models.CharField(default='month', help_text='e.g. month, year, one-time', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('features_list', models.TextField(help_text='Enter features separated by new lines')),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=200)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='api.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
