# Generated by Django 5.1.5 on 2026-02-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chatbot Lead',
                'verbose_name_plural': 'Chatbot Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
