# Generated by Django 5.1.5 on 2026-04-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chatbotlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Roadmap Step',
                'verbose_name_plural': 'Roadmap Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.roadmapstep')),
            ],
            options={
                'verbose_name': 'Roadmap Step Item',
                'ordering': ['order'],
            },
        ),
    ]
